# Generated by Django 3.2 on 2021-06-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0003_useroperation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='billID',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='currencieID',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='function',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='sum',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='operationID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageMoneyApp.useroperation'),
        ),
        migrations.AddField(
            model_name='useroperation',
            name='usersBill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageMoneyApp.usersbill'),
        ),
    ]
