# Generated by Django 3.2 on 2021-06-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0004_auto_20210601_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useroperation',
            old_name='usersBill',
            new_name='billID',
        ),
    ]
