# Generated by Django 3.2 on 2021-06-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0005_rename_usersbill_useroperation_billid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoal',
            name='dateEnd',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usergoal',
            name='dateStart',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='date',
            field=models.CharField(max_length=500),
        ),
    ]
