# Generated by Django 3.2 on 2021-06-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0007_usersstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersstat',
            name='balance',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersstat',
            name='date',
            field=models.CharField(max_length=1000),
        ),
    ]
