# Generated by Django 3.2 on 2021-06-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0008_auto_20210602_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersstat',
            name='balance',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='usersstat',
            name='date',
            field=models.TextField(max_length=1000),
        ),
    ]
