# Generated by Django 3.1.6 on 2021-04-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userSettings',
            new_name='userSetting',
        ),
    ]
