# Generated by Django 3.2 on 2021-05-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0002_auto_20210513_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencie',
            name='value',
            field=models.FloatField(),
        ),
    ]
