# Generated by Django 3.1.6 on 2021-04-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageMoneyApp', '0002_auto_20210404_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='function',
            field=models.BooleanField(),
        ),
    ]
